final

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,12 +1,10 @@
 version: 2.1
 
-
 orbs:
   aws-cli: circleci/aws-cli@3.1.5
   python: circleci/python@2.1.1
 
 commands:
-
   exports:
     steps:
       - run:
@@ -25,154 +23,10 @@ commands:
             echo 'export PROJECT_ROOT_DIR="build-cicd-pipeline/final-project"' >> "$BASH_ENV"
             echo 'export TEMPLATE_ROOT_DIR="build-cicd-pipeline/create-infrastructure"' >> "$BASH_ENV"
             echo 'export PROJECT_TAG="ThaiDG-Udacity-final-project"' >> "$BASH_ENV"
-  
-  destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameter here 
-      stack_name:
-        type: string
-      bucket_name:
-        type: string
-        default: ""
-      when:
-        default: "on_fail"
-        type: enum
-        enum: ["always", "on_success", "on_fail"]
-      aws-access-key-id:
-        default: AWS_ACCESS_KEY_ID
-        description: >
-          AWS access key id for IAM role. Set this to the name of
-          the environment variable you will use to hold this
-          value, i.e. AWS_ACCESS_KEY.
-        type: env_var_name
-      aws-region:
-        default: AWS_DEFAULT_REGION
-        description: >
-          Env var of AWS region to operate in
-          (defaults to AWS_DEFAULT_REGION)
-        type: env_var_name
-      aws-secret-access-key:
-        default: AWS_SECRET_ACCESS_KEY
-        description: >
-          AWS secret key for IAM role. Set this to the name of
-          the environment variable you will use to hold this
-          value, i.e. AWS_SECRET_ACCESS_KEY.
-        type: env_var_name
-      profile-name:
-        default: default
-        description: Profile name to be configured.
-        type: string
-    steps:
-     - run:
-          name: "Install AWS CLI"
-          when: << parameters.when >>
-          command: |
-            if aws --version | grep "aws-cli/" > /dev/null
-            then
-              echo "AWS CLI is already installed, skipping installation."
-              exit 0
-            fi
-
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-     - run:
-          name: "Configure AWS credential"
-          environment:
-            PARAM_AWS_CLI_ACCESS_KEY_ID: <<parameters.aws-access-key-id>>
-            PARAM_AWS_CLI_SECRET_ACCESS_KEY: <<parameters.aws-secret-access-key>>
-            PARAM_AWS_CLI_REGION: <<parameters.aws-region>>
-            PARAM_AWS_CLI_PROFILE_NAME: <<parameters.profile-name>>
-          when: << parameters.when >>
-          command: |
-            if aws --version | grep "aws-cli/" > /dev/null
-            then
-              echo "Due to AWS CLI is already installed, skipping configuration AWS credential."
-              exit 0
-            fi
-
-            PARAM_AWS_CLI_ACCESS_KEY_ID=$(eval echo "\$$PARAM_AWS_CLI_ACCESS_KEY_ID")
-
-            PARAM_AWS_CLI_SECRET_ACCESS_KEY=$(eval echo "\$$PARAM_AWS_CLI_SECRET_ACCESS_KEY")
-
-            PARAM_AWS_CLI_REGION=$(eval echo "\$$PARAM_AWS_CLI_REGION")
-
-            if [ -z "$PARAM_AWS_CLI_ACCESS_KEY_ID" ] || [ -z "${PARAM_AWS_CLI_SECRET_ACCESS_KEY}" ]
-            then
-              echo "Cannot configure profile. AWS access key id and AWS secret access key must be provided."
-              exit 1
-            fi
-
-            aws configure set \
-              aws_access_key_id "$PARAM_AWS_CLI_ACCESS_KEY_ID" \
-              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
-
-            aws configure set \
-              aws_secret_access_key "$PARAM_AWS_CLI_SECRET_ACCESS_KEY" \
-              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
-
-            aws configure set \
-              region "$PARAM_AWS_CLI_REGION" \
-              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
-     - run:
-          name: "Empty << parameters.bucket_name >> bucket"
-          when: << parameters.when >>
-          shell: /bin/bash
-          command: |
-            bucket_name="<< parameters.bucket_name >>"
-
-            if [[ -z $bucket_name ]]
-            then
-              echo "Skip the empty bucket action due to the empty bucket name"
-              exit 0
-            fi
-
-            bucket_uri="s3://$bucket_name"
-            bucket_info=$(aws s3 ls $bucket_uri 2>&1)
-
-            if echo $bucket_info | grep 'NoSuchBucket' > /dev/null
-            then
-              echo "Bucket doesn't exist, skip the empty bucket action"
-              exit 0
-            fi
-
-            # Empty before delete the bucket
-            aws s3 rm $bucket_uri --recursive
-     - run:
-          name: "Delete << parameters.stack_name >> stack"
-          when: << parameters.when >>
-          shell: /bin/bash
-          command: |
-            # Get stack id for the delete_stack waiter
-            stack_info=$(aws cloudformation describe-stacks --stack-name << parameters.stack_name >> --query "Stacks[*] | [0].StackId" 2>&1)
-            if echo $stack_info | grep 'does not exist' > /dev/null
-            then
-              echo "Stack does not exist."
-              echo $stack_info
-              exit 0
-            fi
-            if echo $stack_info | grep 'ValidationError' > /dev/null
-            then
-              echo $stack_info
-              exit 1
-            else
-              aws cloudformation delete-stack --stack-name << parameters.stack_name >>
-              echo $stack_info
-              aws cloudformation wait stack-delete-complete --stack-name $stack_info
-              if [ "<< parameters.when >>" = "on_fail" ]
-              then
-                echo "Roll back completed. Green environment destroyed."
-                exit 0
-              fi
-              echo "Stack << parameters.stack_name >> cleaned up"
-              exit 0
-            fi
 
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: "Revert last migrations"
     parameters:
-      # Add parameter here
       migrations-key:
         type: string
         default: ""
@@ -187,7 +41,7 @@ commands:
         default: REDIS_CLI_USERNAME
       redis-cli-password:
         type: env_var_name
-        default: REDIS_CLI_PASSWORD   
+        default: REDIS_CLI_PASSWORD
     steps:
       - run:
           name: "Install redis-cli"
@@ -240,6 +94,147 @@ commands:
             # Revert migration on fail
             npm run migrations:revert
 
+  destroy_environment:
+    parameters:
+      stack_name:
+        type: string
+      bucket_name:
+        type: string
+        default: ""
+      when:
+        default: "on_fail"
+        type: enum
+        enum: ["always", "on_success", "on_fail"]
+      aws-access-key-id:
+        default: AWS_ACCESS_KEY_ID
+        description: >
+          AWS access key id for IAM role. Set this to the name of
+          the environment variable you will use to hold this
+          value, i.e. AWS_ACCESS_KEY.
+        type: env_var_name
+      aws-region:
+        default: AWS_DEFAULT_REGION
+        description: >
+          Env var of AWS region to operate in
+          (defaults to AWS_DEFAULT_REGION)
+        type: env_var_name
+      aws-secret-access-key:
+        default: AWS_SECRET_ACCESS_KEY
+        description: >
+          AWS secret key for IAM role. Set this to the name of
+          the environment variable you will use to hold this
+          value, i.e. AWS_SECRET_ACCESS_KEY.
+        type: env_var_name
+      profile-name:
+        default: default
+        description: Profile name to be configured.
+        type: string
+    steps:
+      - run:
+          name: "Install AWS CLI"
+          when: << parameters.when >>
+          command: |
+            if aws --version | grep "aws-cli/" > /dev/null
+            then
+              echo "AWS CLI is already installed, skipping installation."
+              exit 0
+            fi
+
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - run:
+          name: "Configure AWS credential"
+          environment:
+            PARAM_AWS_CLI_ACCESS_KEY_ID: <<parameters.aws-access-key-id>>
+            PARAM_AWS_CLI_SECRET_ACCESS_KEY: <<parameters.aws-secret-access-key>>
+            PARAM_AWS_CLI_REGION: <<parameters.aws-region>>
+            PARAM_AWS_CLI_PROFILE_NAME: <<parameters.profile-name>>
+          when: << parameters.when >>
+          command: |
+            if aws --version | grep "aws-cli/" > /dev/null
+            then
+              echo "Due to AWS CLI is already installed, skipping configuration AWS credential."
+              exit 0
+            fi
+
+            PARAM_AWS_CLI_ACCESS_KEY_ID=$(eval echo "\$$PARAM_AWS_CLI_ACCESS_KEY_ID")
+
+            PARAM_AWS_CLI_SECRET_ACCESS_KEY=$(eval echo "\$$PARAM_AWS_CLI_SECRET_ACCESS_KEY")
+
+            PARAM_AWS_CLI_REGION=$(eval echo "\$$PARAM_AWS_CLI_REGION")
+
+            if [ -z "$PARAM_AWS_CLI_ACCESS_KEY_ID" ] || [ -z "${PARAM_AWS_CLI_SECRET_ACCESS_KEY}" ]
+            then
+              echo "Cannot configure profile. AWS access key id and AWS secret access key must be provided."
+              exit 1
+            fi
+
+            aws configure set \
+              aws_access_key_id "$PARAM_AWS_CLI_ACCESS_KEY_ID" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+
+            aws configure set \
+              aws_secret_access_key "$PARAM_AWS_CLI_SECRET_ACCESS_KEY" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+
+            aws configure set \
+              region "$PARAM_AWS_CLI_REGION" \
+              --profile "$PARAM_AWS_CLI_PROFILE_NAME"
+      - run:
+          name: "Empty << parameters.bucket_name >> bucket"
+          when: << parameters.when >>
+          shell: /bin/bash
+          command: |
+            bucket_name="<< parameters.bucket_name >>"
+
+            if [[ -z $bucket_name ]]
+            then
+              echo "Skip the empty bucket action due to the empty bucket name"
+              exit 0
+            fi
+
+            bucket_uri="s3://$bucket_name"
+            bucket_info=$(aws s3 ls $bucket_uri 2>&1)
+
+            if echo $bucket_info | grep 'NoSuchBucket' > /dev/null
+            then
+              echo "Bucket doesn't exist, skip the empty bucket action"
+              exit 0
+            fi
+
+            # Empty before delete the bucket
+            aws s3 rm $bucket_uri --recursive
+      - run:
+          name: "Delete << parameters.stack_name >> stack"
+          when: << parameters.when >>
+          shell: /bin/bash
+          command: |
+            # Get stack id for the delete_stack waiter
+            stack_info=$(aws cloudformation describe-stacks --stack-name << parameters.stack_name >> --query "Stacks[*] | [0].StackId" 2>&1)
+            if echo $stack_info | grep 'does not exist' > /dev/null
+            then
+              echo "Stack does not exist."
+              echo $stack_info
+              exit 0
+            fi
+            if echo $stack_info | grep 'ValidationError' > /dev/null
+            then
+              echo $stack_info
+              exit 1
+            else
+              aws cloudformation delete-stack --stack-name << parameters.stack_name >>
+              echo $stack_info
+              aws cloudformation wait stack-delete-complete --stack-name $stack_info
+              if [ "<< parameters.when >>" = "on_fail" ]
+              then
+                echo "Roll back completed. Green environment destroyed."
+                exit 0
+              fi
+              echo "Stack << parameters.stack_name >> cleaned up"
+              exit 0
+            fi
+  
   deploy_stack:
     parameters:
       stack_name:
@@ -260,20 +255,21 @@ commands:
             --region us-east-1 \
             --tags Project="ThaiDG-Udacity-final-project" \
             --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"
-            
+
 jobs:
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
+      # This command will pull all of the files into a directory called project which can be found at ~/project.
       - checkout
+      # Export environment variable
       - exports
       - restore_cache:
           keys: [frontend-build]
       - run:
-          name: Build front-end
+          name: Build frontend
           command: |
-            # Your code here
             cd $(eval echo "$CIRCLE_WORKING_DIRECTORY/$PROJECT_ROOT_DIR/frontend")
             npm install
             npm run build
@@ -285,7 +281,9 @@ jobs:
     docker:
       - image: circleci/node:13.8.0
     steps:
+      # This command will pull all of the files into a directory called project which can be found at ~/project.
       - checkout
+      # Export environment variable
       - exports
       - restore_cache:
           keys: [backend-build]
@@ -305,19 +303,18 @@ jobs:
             echo TYPEORM_PORT=$TYPEORM_PORT >> .env
             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
       - run:
-          name: Back-end build
+          name: Build backend
           command: |
-             # Your code here
-              cd $(eval echo "$CIRCLE_WORKING_DIRECTORY/$PROJECT_ROOT_DIR/backend")
-              npm install
-              npm run build
-              cd ..
-              # Compress the backend folder
-              tar -C backend -czvf artifact-backend.tar.gz .
-              # no error if existing, make parent directories as needed
-              mkdir --parents $WORKSPACE_DIR
-              # Move the compressed file to workspace folder
-              mv artifact-backend.tar.gz $WORKSPACE_DIR/artifact-backend.tar.gz
+            cd $(eval echo "$CIRCLE_WORKING_DIRECTORY/$PROJECT_ROOT_DIR/backend")
+            npm install
+            npm run build
+            cd ..
+            # Compress the backend folder
+            tar -C backend -czvf artifact-backend.tar.gz .
+            # no error if existing, make parent directories as needed
+            mkdir --parents $WORKSPACE_DIR
+            # Move the compressed file to workspace folder
+            mv artifact-backend.tar.gz $WORKSPACE_DIR/artifact-backend.tar.gz
       - persist_to_workspace:
           root: /home/circleci/workspace
           paths:
@@ -328,49 +325,45 @@ jobs:
 
   test-frontend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      # This command will pull all of the files into a directory called project which can be found at ~/project.
       - checkout
+      # Export environment variable
       - exports
-      # Restore from cache
       - restore_cache:
           keys: [frontend-build]
-      # Your job code here
       - run:
           name: Test frontend
           command: |
             cd $(eval echo "$CIRCLE_WORKING_DIRECTORY/$PROJECT_ROOT_DIR/frontend")
             npm install
             npm run test
-                
+
   test-backend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      # This command will pull all of the files into a directory called project which can be found at ~/project.
       - checkout
+      # Export environment variable
       - exports
-      # Restore from cache
       - restore_cache:
           keys: [backend-build]
-      # Your job code here
       - run:
           name: Test backend
           command: |
             cd $(eval echo "$CIRCLE_WORKING_DIRECTORY/$PROJECT_ROOT_DIR/backend")
             npm install
             npm run test
-            
+
   scan-frontend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      # This command will pull all of the files into a directory called project which can be found at ~/project.
       - checkout
+      # Export environment variable
       - exports
       # Restore from cache
       - restore_cache:
